### ISSUE TITLE
Secondary feature annotations (helix, ES, etc)

### ISSUE THREAD

**Issue by joegeorgeson** [RNAcentral/R2DT#107]
Dear R2DT developers.

Have you generated or are you aware of any of your references containing secondary structure annotations like;
```
h34:1267–1317
h45:1751–1800
```
I see that many of the reference datasets used by R2DT possess these annotations but I'm unable to find them in a format that can be accessed programmatically via a text file.

Thank you very much,
Joe

**Comment by AntonPetrov** [comment]
@joegeorgeson Hi Joe! Thank you for your interest in R2DT. We don't have this information readily available in R2DT but this is something that would be useful to include in templates in a machine readable way.

@aspetr01 Anton, do you happen to have these annotations in RiboVision or perhaps in the CRW mirror?

**Comment by AntonPetrov** [comment]
Seems like there was some productive email discussion so closing the issue for now. Feel free to reopen, if needed.
