### ISSUE TITLE
Considerations for external implementations of R2DT  widget

### ISSUE THREAD

**Issue by ValWood** [RNAcentral/R2DT#137]
Hi,

@kimrutherford has  just implemented the RNA 2ndary structure widget at PomBase (thank you for providing this)

You can see  the implementation here:
https://www.pombase.org/gene/SPSNRNA.01

As you can see we have issues with  integration visually . Ideally, we would like to include it in our  summary panel as we do for JBrowse/ AlphaFold/pdb/ etc with proteins
e.g.
https://www.pombase.org/gene/SPBC32H8.04c
so that we can toggle between them. 
You can see in this example that  we are able to arrange the pdb widget components so that the key it to the side of the viewer.

However, we are unable to do this because we can't configure the positioning of the key and the legend.

The "title" is also problematic for hosting on other sites as we have our own style headings, we need to remove our house style heading to avoid a heading duplication.

I realise this may not be top of your priorities, but it will make it more easily usable by external groups.

Thanks, 
v

**Comment by AntonPetrov** [comment]
@ValWood Hi Val! 

It is great to see R2DT used in PomBase 🎉 and thank you for writing up your feedback, it is really useful!

I will raise separate issues based on your comments in the [r2dt-web](https://github.com/RNAcentral/r2dt-web) repo and will work it into the R2DT roadmap. Hopefully you will be able to use R2DT in the summary panel in a not too distant future! 🤞

**Comment by ValWood** [comment]
Great! tag me and Kim in the new tickets.
I know SGD and flybase already use it. I was trying to see if they had similar issues.

I could not find examples in flybase on any of the tRNA or rRNA pages that I looked at @sjm41  where can we see these?
This might account for why SGD opted for a "thumbnail" rather than the full functionality.

**Comment by AntonPetrov** [comment]
Just a quick note to that if you do something like `customStyle='{"titleSize": "0px"}'` then the title is effectively hidden.

You can see examples of other resources using R2DT here: https://docs.r2dt.bio/en/latest/#who-uses-r2dt

**Comment by sjm41** [comment]
@ValWood  Here's a tRNA example (somewhat buried within the 'Gene Model and Products' -> Structure section of the report): http://flybase.org/reports/FBgn0011954.htm#gene_model_products

![Screenshot 2024-06-20 at 12 40 43](https://github.com/RNAcentral/R2DT/assets/16306861/6177789d-0253-4111-a1d7-40ce96683c2b)

**Comment by ValWood** [comment]
Thanks @sjm41 , I see, you have more space to play with ;)

**Comment by AntonPetrov** [comment]
Thanks a lot everyone! I will close this issue and we can continue with more specific ones in r2dt-web.
