### ISSUE TITLE
Add support for pseudoknot visualisation

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/R2DT#4]
Example commands to include pseudoknot in Infernal output:

- `cmbuild my.cm my.sto`
- `cmalign --mapali my.sto --mapstr my.cm new.fa > new.sto`

`new.sto` will have the pknot annotation from `my.sto`, but also will have sequences from `my.sto` in addition to sequences in `new.fa`. It's possible to remove `my.sto` sequences with `esl-alimanip`

**Comment by ababaian** [comment]
Hello Anton, I'm just about to start making some templates for the deltavirus ribozyme as it is commonly drawn in the literature (see below). I thought I'd ask if this is possible before diving in. The current RFAM model is missing the pseudoknot depiction. Can I wrangle R2DT to draw these in the conformation shown below?

![dvrz](https://user-images.githubusercontent.com/9220907/112420610-bad9bd80-8cea-11eb-87e8-59ca860b3639.png)

**Comment by AntonPetrov** [comment]
Hi Artem! Thank you for your interest in R2DT. 

You are correct, the R2DT diagrams for RF00094 do not show the pseudoknot, for example:

<img width="691" alt="Screenshot 2021-03-25 at 10 28 51" src="https://user-images.githubusercontent.com/432675/112458636-e5f8f700-8d54-11eb-921c-3a6896bdb590.png">

With the current version of R2DT, one could update the [RF00094 template](https://github.com/RNAcentral/R2DT/tree/master/data/rfam/RF00094) to make the layout follow your example, but the basepair lines will only be displayed for the nested basepairs, not the pseudoknot. 

However, @davidhoksza implemented support for pseudoknots in Traveler so we could look into this in more detail and try to get the pseudoknot display to work too.

Feel free to let me know if you need any help in case you decide to have a go at making a new template!

**Comment by AntonPetrov** [comment]
Implemented in [release 1.4](https://docs.r2dt.bio/en/latest/blog/2023-09-release-1.4.html)
