### ISSUE TITLE
Make R2DT command line tool available as Bioconda package

### ISSUE THREAD

**Issue by janstrauss1** [RNAcentral/R2DT#53]
Hi there,

I'd like to try `R2DT` as a command line tool.

While I know that there are is the possibility of installing `R2DT` from [Docker Hub](https://hub.docker.com/r/rnacentral/r2dt), I was wondering if it would be possible for you to also make `R2DT` available as a Bioconda package from https://anaconda.org/bioconda/repo, too?

Many thanks in advance for any feedback!

**Comment by blakesweeney** [comment]
Hi, thanks for your interest in R2DT. I will look into making this into a package for bioconda shortly. I will keep you posted on it. Thanks!

**Comment by blakesweeney** [comment]
Hi, it looks like we won't have the bandwidth to maintain bioconda packages ourselves. We are happy to have anyone else do it, of course.
