### ISSUE TITLE
Fail to representing the my sequence ( tRNA-Ser)

### ISSUE THREAD

**Issue by bombumbom** [RNAcentral/R2DT#68]
I employed this program for my mitochondrial data tRNA secondary structure analysis. All other tRNAs gave good results but failed for Ser. Perhaps it is because it has an incomplete structure.
I would also like to draw a picture of an incomplete structure, such as in tRNAscan-SE. Is there any way to present a diagram even if it has an incomplete structure like Ser?

It is the sequence of tRAN-Ser.
>tRNA-Ser
GAACCTGACCGGATTAACGAGAACTGCTAATTACTCGCCACTGAAGTTCAACTCCTCAGCAGGTTCG

Thank you

**Comment by patriciaplchan** [comment]
The templates currently included in R2DT for tRNAs do not support mt-tRNA-Ser that is missing the D-arm. We are developing a new set of templates specifically designed for mt-tRNAs in vertebrates. 

To get a secondary structure image for your mt-tRNA-Ser, you can use the tRNAscan-SE web server at http://trna.ucsc.edu/tRNAscan-SE/ and submit the sequence for prediction. At the result table, click on the View button for Predicted tRNA structure. It will then provide a secondary structure image.

**Comment by bombumbom** [comment]
I hope to develop quickly.
I will wait for these.

Thank you.

**Comment by bombumbom** [comment]
I want to develop quickly.
I will wait for these.

Thank you.
