### ISSUE TITLE
Integrate with an interactive editing interface

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/R2DT#73]
- [x] update to the latest Traveler
- [x] generate additional JSON output files that contain the secondary structure layout described using JSON schema

To make the feature available to the users:

- [x] add JSON files to the Job Dispatcher API so that the rnacentral.org/r2dt web app can have editable output 
- [ ] generate and store JSON files when precomputing structures in RNAcentral so that every structure in RNAcentral can be edited
- [ ] the R2DT widget needs to show a link to the visualisation client that can load the JSON file and make it editable

**Comment by AntonPetrov** [comment]
Hi Fabio @biomadeira 👋 Hope you had a nice Jubilee weekend 👑

We are working on a new R2DT release that will support JSON output. These new files will allow us to connect R2DT with an interactive online editor so that the users will be able to edit the diagrams and manually annotate them. The JS editor already exists, so as soon as we have the new API it should all work right away 🤞

Would you be able to deploy a new R2DT version on wwwdev and add JSON as a supported output type to the JD API please? The `rnacentral/r2dt:develop` Docker image has the new code and you'll also need a [new precomputed library](https://www.icloud.com/iclouddrive/0e3e4Q-eldLHVVlpnEm6d6HcA#cms).

I have a guest EBI Slack account but I can't message you there unless @blakesweeney adds you to the #R2DT channel that I am a member of. For now, let's keep the discussion on GitHub, if that's okay with you.

Please let me know if you have any questions or need further information. Thanks in advance!

CC @carlosribas @blakesweeney

**Comment by biomadeira** [comment]
Hi @AntonPetrov 

I can certainly work on this. I will let you know when I have it ready for you to test.

Best regards

**Comment by biomadeira** [comment]
Hi @AntonPetrov

This is ready for testing in our wwwdev server. 

Best regards!

**Comment by AntonPetrov** [comment]
@biomadeira This is amazing, thank you so much for doing this so quickly Fabio! 🥇 

I tried testing it by submitting a sequence to wwwdev using curl and then fetching results, but it looks like R2DT crashes because it does not see the input sequence 😞

Here is my log:

```
$ curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: text/plain' -d 'email=myemail%40gmail.com&title=test&sequence=GUCUACGGCCAUACCACCCUGAACGCGCCCGAUCUCGUCUGAUCUCGGAAGCUAAGCAGGGUCGGGCCUGGUUAGUACUUGGAUGGGAGACCGCCUGGGAAUACCGGGUGCUGUAGGCUUU' 'https://wwwdev.ebi.ac.uk/Tools/services/rest/r2dt/run'

r2dt-R20220608-223836-0205-18454110-np2

$ curl -X GET --header 'Accept: text/plain' 'https://wwwdev.ebi.ac.uk/Tools/services/rest/r2dt/status/r2dt-R20220608-223836-0205-18454110-np2'

FINISHED

$ curl --output test-api.tar.gz -X GET --header 'Accept: application/json' 'https://wwwdev.ebi.ac.uk/Tools/services/rest/r2dt/result/r2dt-R20220608-223836-0205-18454110-np2/r2dt'
```

And then inside the `rfam` folder in the `rfam.ribotyper.log` file it says:

```
# Validating input files                                                           ... 
ERROR in ribo_RunCommand(), the following command failed:
/rna/infernal-1.1.2/bin/esl-sfetch --index r2dt-R20220608-223836-0205-18454110-np2.sequence > /dev/null

# RIBO-FAILURE
```

It seems like the file `r2dt-R20220608-223836-0205-18454110-np2.sequence` does not exist or is empty or is malformed in some way. Could you please take a look, or am I missing something?

**Comment by biomadeira** [comment]
Hi @AntonPetrov 
I think there is an  issue with your input sequence as it is not in fasta format. I can see this in stderr
```
Parse failed (sequence file r2dt-R20220608-223836-0205-18454110-np2/subset.fasta):
Line 1: unexpected char G; expected FASTA to start with >

Format of file r2dt-R20220608-223836-0205-18454110-np2.sequence unrecognized.

ERROR in ribo_RunCommand(), the following command failed:
/rna/infernal-1.1.2/bin/esl-sfetch --index r2dt-R20220608-223836-0205-18454110-np2.sequence > /dev/null
```
The example I ran using a sequence in fasta worked as expected.

**Comment by AntonPetrov** [comment]
Hi Anton @aspetr01 and Caeden @CaedenM! As you can see from the discussion above, it's now possible to fetch R2DT results in the RNA 2D JSON Schema format from the test API. 

Everything should be ready to add an **Edit** button to the R2DT web application, as long as Caeden's code can load the JSON data given an R2DT job id similar to this:

https://wwwdev.ebi.ac.uk/Tools/services/rest/r2dt/result/r2dt-R20220609-154733-0803-79709511-np2/json

For example, it would be great if we could simply link to `http://<some domain>/edit2d/<r2dt job id>` and the page would be initialised with the R2DT job id json data and show the RNA 2D editing interface. There could be other solutions so let me know if you have a better idea.

Could you please give it a go and let me know if you run into any issues here or on Slack? Thank you for working on this!

CC @blakesweeney @carlosribas

**Comment by AntonPetrov** [comment]
@aspetr01 @caedenM 

Here is a fresh example link:
https://wwwdev.ebi.ac.uk/Tools/services/rest/r2dt/result/r2dt-R20220628-215952-0884-19016079-np2/json

The link in the previous message expired because the results are deleted after 7 days. You can get a new job id (like `r2dt-R20220628-215952-0884-19016079-np2`) by submitting any sequence at https://test.rnacentral.org/r2dt. Please note that since you need to use the test website because the JSON output is not available in production yet.

**Comment by AntonPetrov** [comment]
I've uploaded an example JSON file for posterity:

[r2dt-R20220628-215952-0884-19016079-np2.json.txt](https://github.com/RNAcentral/R2DT/files/9004877/r2dt-R20220628-215952-0884-19016079-np2.json.txt)

**Comment by AntonPetrov** [comment]
This [has been implemented](https://docs.r2dt.bio/en/latest/editors.html) in RNAcanvas and XRNA-React now. Thanks everyone!
